[2024-12-21 11:10:24,137: INFO: main: welcome to our custom log]
[2024-12-21 11:10:50,015: INFO: main: welcome to our custom log]
[2024-12-21 14:07:53,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 14:08:01,308: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 14:09:06,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 14:40:22,924: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 14:40:28,820: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 14:49:25,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 14:53:41,008: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 15:00:53,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-21 15:15:51,322: INFO: common: created directory at: artifacts]
[2024-12-21 15:15:51,324: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-21 15:15:51,326: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-21 15:19:30,829: INFO: common: created directory at: artifacts]
[2024-12-21 15:19:30,832: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-21 15:19:30,835: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-21 15:21:41,852: INFO: common: created directory at: artifacts]
[2024-12-21 15:21:41,854: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-21 15:21:41,856: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-22 14:57:56,131: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-22 14:57:56,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-22 14:57:56,151: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-22 14:57:56,152: INFO: common: created directory at: artifacts]
[2024-12-22 14:57:56,153: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-22 14:57:56,153: ERROR: main: name 'DataIngestion' is not defined]
Traceback (most recent call last):
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 14, in main
    data_ingestion = DataIngestion(config=data_ingestion_config)
NameError: name 'DataIngestion' is not defined
[2024-12-22 14:59:14,184: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-22 14:59:14,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-22 14:59:14,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-22 14:59:14,186: INFO: common: created directory at: artifacts]
[2024-12-22 14:59:14,187: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-22 14:59:14,187: ERROR: main: name 'DataIngestion' is not defined]
Traceback (most recent call last):
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 14, in main
    data_ingestion = DataIngestion(config=data_ingestion_config)
NameError: name 'DataIngestion' is not defined
[2024-12-22 14:59:25,508: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-22 14:59:25,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-22 14:59:25,514: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-22 14:59:25,517: INFO: common: created directory at: artifacts]
[2024-12-22 14:59:25,518: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-22 14:59:25,519: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-22 15:01:20,076: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-22 15:01:34,684: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-25 14:25:11,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 14:25:11,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 14:25:11,401: INFO: common: created directory at: artifacts]
[2024-12-25 14:26:54,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 14:26:54,500: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 14:26:54,505: INFO: common: created directory at: artifacts]
[2024-12-25 14:56:12,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 14:56:12,177: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 14:56:12,180: INFO: common: created directory at: artifacts]
[2024-12-25 14:56:12,183: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-25 14:56:22,877: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-25 16:06:15,847: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-25 16:06:15,850: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:06:15,852: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:06:15,853: INFO: common: created directory at: artifacts]
[2024-12-25 16:06:15,854: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-25 16:06:15,854: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-25 16:08:27,191: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-25 16:08:41,429: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-25 16:23:52,568: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:23:52,584: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:23:52,587: INFO: common: created directory at: artifacts]
[2024-12-25 16:23:52,588: INFO: common: created directory at: artifacts\training]
[2024-12-25 16:24:48,406: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-12-25 16:24:49,408: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-25 16:24:49,410: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:24:49,413: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:24:49,414: INFO: common: created directory at: artifacts]
[2024-12-25 16:24:49,414: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-25 16:24:49,415: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-25 16:27:52,620: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-25 16:28:09,847: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-25 16:28:09,848: INFO: main: *******************]
[2024-12-25 16:28:09,849: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-25 16:28:09,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:28:09,854: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:28:09,855: INFO: common: created directory at: artifacts]
[2024-12-25 16:28:09,857: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-25 16:28:10,624: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-25 16:28:10,919: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-25 16:28:49,191: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-12-25 16:28:49,899: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-25 16:28:49,902: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:28:49,904: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:28:49,906: INFO: common: created directory at: artifacts]
[2024-12-25 16:28:49,906: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-25 16:28:49,907: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-25 16:29:28,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:29:28,334: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:29:28,337: INFO: common: created directory at: artifacts]
[2024-12-25 16:29:28,338: INFO: common: created directory at: artifacts\training]
[2024-12-25 16:31:34,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:31:34,550: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:31:34,553: INFO: common: created directory at: artifacts]
[2024-12-25 16:31:34,556: INFO: common: created directory at: artifacts\training]
[2024-12-25 16:31:35,215: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-25 16:32:08,044: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-25 16:32:08,077: INFO: main: *******************]
[2024-12-25 16:32:08,085: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-25 16:32:08,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 16:32:08,135: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 16:32:08,160: INFO: common: created directory at: artifacts]
[2024-12-25 16:32:08,172: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-25 16:32:09,745: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-25 16:32:11,328: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-25 23:34:34,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-25 23:34:34,072: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-25 23:34:34,074: INFO: common: created directory at: artifacts]
[2024-12-25 23:34:34,076: INFO: common: created directory at: artifacts\training]
[2024-12-26 11:01:30,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-26 11:01:30,628: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-26 11:01:30,631: INFO: common: created directory at: artifacts]
[2024-12-26 11:01:30,634: INFO: common: created directory at: artifacts\training]
[2024-12-26 11:14:17,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-26 11:14:17,556: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-26 11:14:17,559: INFO: common: created directory at: artifacts]
[2024-12-26 11:14:17,561: INFO: common: created directory at: artifacts\training]
[2024-12-26 14:27:37,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-26 14:27:37,147: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-26 14:27:37,149: INFO: common: created directory at: artifacts]
[2024-12-26 14:27:37,151: INFO: common: created directory at: artifacts\training]
[2024-12-26 14:27:56,254: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-26 14:27:56,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-26 14:27:56,267: INFO: common: created directory at: artifacts]
[2024-12-26 14:27:56,268: INFO: common: created directory at: artifacts\training]
[2024-12-26 15:55:27,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-26 15:55:27,751: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-26 15:55:27,753: INFO: common: created directory at: artifacts]
[2024-12-26 15:55:27,754: INFO: common: created directory at: artifacts\training]
[2024-12-27 11:40:09,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-27 11:40:10,010: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-27 11:40:10,014: INFO: common: created directory at: artifacts]
[2024-12-27 11:40:10,019: INFO: common: created directory at: artifacts\training]
[2024-12-28 07:03:01,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-28 07:03:01,864: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-28 07:03:01,865: INFO: common: created directory at: artifacts]
[2024-12-28 07:03:01,867: INFO: common: created directory at: artifacts\training]
[2024-12-29 14:58:17,534: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-29 14:58:17,554: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-29 14:58:17,558: INFO: common: created directory at: artifacts]
[2024-12-29 14:58:17,560: INFO: common: created directory at: artifacts\training]
[2024-12-30 20:23:42,345: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-12-30 20:23:44,823: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-30 20:23:44,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-30 20:23:44,877: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-30 20:23:44,879: INFO: common: created directory at: artifacts]
[2024-12-30 20:23:44,882: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-30 20:23:44,883: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-30 20:27:14,086: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-30 20:27:43,905: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-30 20:27:43,906: INFO: main: *******************]
[2024-12-30 20:27:43,908: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-30 20:27:43,913: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-30 20:27:43,919: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-30 20:27:43,921: INFO: common: created directory at: artifacts]
[2024-12-30 20:27:43,922: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-30 20:27:45,503: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-30 20:27:46,155: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-30 20:27:46,155: INFO: main: *******************]
[2024-12-30 20:27:46,155: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-30 20:27:46,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-30 20:27:46,172: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-30 20:27:46,174: INFO: common: created directory at: artifacts]
[2024-12-30 20:27:46,179: INFO: common: created directory at: artifacts\training]
[2024-12-31 08:52:02,725: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-31 21:58:15,049: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-31 21:58:15,085: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-31 21:58:15,091: INFO: common: created directory at: artifacts]
[2024-12-31 22:06:06,807: INFO: common: json file saved at: scores.json]
[2024-12-31 22:06:10,301: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-31 22:06:11,058: INFO: builder_impl: Assets written to: C:\Users\admin\AppData\Local\Temp\tmptj91it_z\model\data\model\assets]
[2024-12-31 22:15:44,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-31 22:15:44,361: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-31 22:15:44,363: INFO: common: created directory at: artifacts]
[2024-12-31 22:23:11,700: INFO: common: json file saved at: scores.json]
[2024-12-31 22:23:15,175: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-31 22:23:16,182: INFO: builder_impl: Assets written to: C:\Users\admin\AppData\Local\Temp\tmp6cujjnos\model\data\model\assets]
[2024-12-31 22:49:30,980: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-31 22:49:30,984: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-31 22:49:30,987: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-31 22:49:30,988: INFO: common: created directory at: artifacts]
[2024-12-31 22:49:30,989: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-31 22:49:30,989: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-31 22:51:52,669: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-31 22:52:20,873: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-31 22:52:20,873: INFO: main: *******************]
[2024-12-31 22:52:20,875: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-31 22:52:20,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-31 22:52:20,891: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-31 22:52:20,892: INFO: common: created directory at: artifacts]
[2024-12-31 22:52:20,893: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-31 22:52:22,149: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-31 22:52:22,784: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-31 22:52:22,785: INFO: main: *******************]
[2024-12-31 22:52:22,785: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-31 22:52:22,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-31 22:52:22,796: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-31 22:52:22,797: INFO: common: created directory at: artifacts]
[2024-12-31 22:52:22,800: INFO: common: created directory at: artifacts\training]
[2025-01-01 15:55:48,542: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-01 15:55:48,548: INFO: main: *******************]
[2025-01-01 15:55:48,548: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-01 15:55:48,574: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 15:55:48,595: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 15:55:48,600: INFO: common: created directory at: artifacts]
[2025-01-01 16:05:17,682: INFO: common: json file saved at: scores.json]
[2025-01-01 16:05:17,685: INFO: common: json file saved at: scores.json]
[2025-01-01 16:05:17,686: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-01-01 16:27:54,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 16:27:54,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 16:27:54,081: INFO: common: created directory at: artifacts]
[2025-01-01 16:32:54,294: INFO: common: json file saved at: scores.json]
[2025-01-01 16:32:57,641: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-01 16:32:58,407: INFO: builder_impl: Assets written to: C:\Users\admin\AppData\Local\Temp\tmpyy2tw376\model\data\model\assets]
[2025-01-01 16:34:52,621: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 16:34:52,632: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 16:34:52,634: INFO: common: created directory at: artifacts]
[2025-01-01 16:39:46,196: INFO: common: json file saved at: scores.json]
[2025-01-01 16:39:49,100: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-01 16:39:49,704: INFO: builder_impl: Assets written to: C:\Users\admin\AppData\Local\Temp\tmpnxzg6o7v\model\data\model\assets]
[2025-01-01 18:28:02,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 18:28:02,440: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 18:28:02,442: INFO: common: created directory at: artifacts]
[2025-01-01 18:33:54,856: INFO: common: json file saved at: scores.json]
[2025-01-01 18:33:58,309: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-01 18:33:59,077: INFO: builder_impl: Assets written to: C:\Users\admin\AppData\Local\Temp\tmpkqib1epc\model\data\model\assets]
[2025-01-01 19:02:49,600: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-01 19:02:49,613: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 19:02:49,616: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 19:02:49,617: INFO: common: created directory at: artifacts]
[2025-01-01 19:02:49,619: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-01 19:02:49,621: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-01 19:04:52,537: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-01 19:05:21,728: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-01 19:09:57,265: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-01 19:09:57,268: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 19:09:57,271: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 19:09:57,273: INFO: common: created directory at: artifacts]
[2025-01-01 19:09:57,273: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-01 19:09:57,273: INFO: data_injestion: Downloading data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-01 19:12:28,296: INFO: data_injestion: Downloaded data from https://drive.google.com/file/d/1n7jD1lU3Bi-J1M_JjP863Y_SYgGn5PeJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-01 19:12:43,415: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-01 19:14:53,958: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-01 19:14:55,459: INFO: stage_02_prepare_base_model: *******************]
[2025-01-01 19:14:55,460: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-01 19:14:55,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 19:14:55,471: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 19:14:55,472: INFO: common: created directory at: artifacts]
[2025-01-01 19:14:55,474: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-01 19:14:56,369: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-01 19:14:56,729: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-01 19:15:06,008: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-01 19:15:06,603: INFO: stage_03_model_training: *******************]
[2025-01-01 19:15:06,604: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-01-01 19:15:06,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 19:15:06,607: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 19:15:06,608: INFO: common: created directory at: artifacts]
[2025-01-01 19:15:06,608: INFO: common: created directory at: artifacts\training]
[2025-01-01 23:25:02,351: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-01 23:25:03,346: INFO: stage_02_prepare_base_model: *******************]
[2025-01-01 23:25:03,347: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-01 23:25:03,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 23:25:03,350: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 23:25:03,350: INFO: common: created directory at: artifacts]
[2025-01-01 23:25:03,351: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-01 23:25:03,804: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-01 23:25:04,018: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-01 23:25:13,686: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-01 23:25:14,308: INFO: stage_03_model_training: *******************]
[2025-01-01 23:25:14,308: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-01-01 23:25:14,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-01 23:25:14,312: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-01 23:25:14,312: INFO: common: created directory at: artifacts]
[2025-01-01 23:25:14,313: INFO: common: created directory at: artifacts\training]
[2025-01-02 09:12:54,096: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-02 09:12:55,762: INFO: stage_03_model_training: *******************]
[2025-01-02 09:12:55,764: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-01-02 09:12:55,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-02 09:12:55,789: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-02 09:12:55,790: INFO: common: created directory at: artifacts]
[2025-01-02 09:12:55,790: INFO: common: created directory at: artifacts\training]
[2025-01-02 19:40:04,710: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-02 19:40:19,285: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-02 19:40:22,376: INFO: stage_04_model_evaluation: *******************]
[2025-01-02 19:40:22,377: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-02 19:40:22,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-02 19:40:22,390: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-02 19:40:22,392: INFO: common: created directory at: artifacts]
[2025-01-02 19:45:44,667: INFO: common: json file saved at: scores.json]
[2025-01-02 19:45:44,670: INFO: common: json file saved at: scores.json]
[2025-01-02 19:45:44,671: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-01-03 13:15:54,450: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 13:15:55,314: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.44.1.230:8080]
[2025-01-03 13:15:55,315: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 13:17:33,211: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:17:33] "GET / HTTP/1.1" 200 -]
[2025-01-03 13:18:00,136: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-03 13:18:00,149: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:18:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 13:19:05,604: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:19:05] "GET / HTTP/1.1" 200 -]
[2025-01-03 13:19:20,313: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-03 13:19:20,315: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:19:20] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 13:30:12,823: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.44.1.230:8080]
[2025-01-03 13:30:12,824: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 13:31:08,297: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:31:08] "GET / HTTP/1.1" 200 -]
[2025-01-03 13:31:42,664: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-03 13:31:42,677: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:31:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 13:35:25,105: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.44.1.230:8080]
[2025-01-03 13:35:25,105: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 13:37:54,105: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:37:54] "GET / HTTP/1.1" 200 -]
[2025-01-03 13:38:14,063: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\admin\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-03 13:38:14,070: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:38:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 13:48:42,612: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.44.1.230:8080]
[2025-01-03 13:48:42,613: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 13:48:53,004: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:48:53] "GET / HTTP/1.1" 200 -]
[2025-01-03 13:49:18,642: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:49:18] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 13:53:23,419: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 13:53:23] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 14:03:33,661: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.44.1.230:8080]
[2025-01-03 14:03:33,661: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 14:03:43,435: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 14:03:43] "GET / HTTP/1.1" 200 -]
[2025-01-03 14:03:52,213: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 14:03:52] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 20:55:05,747: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 20:55:08,109: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.20.10.2:8080]
[2025-01-03 20:55:08,109: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 20:55:43,930: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 20:55:43] "GET / HTTP/1.1" 200 -]
[2025-01-03 20:55:59,710: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 45, in predictRoute
    return jsonify(result)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\admin\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\admin\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\admin\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type float32 is not JSON serializable
[2025-01-03 20:55:59,730: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 20:55:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 20:56:40,820: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 20:56:40] "GET / HTTP/1.1" 200 -]
[2025-01-03 20:56:53,638: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 45, in predictRoute
    return jsonify(result)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\admin\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\admin\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\admin\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type float32 is not JSON serializable
[2025-01-03 20:56:53,643: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 20:56:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 20:58:44,112: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 20:58:45,015: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.20.10.2:8080]
[2025-01-03 20:58:45,016: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 20:59:01,414: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 20:59:01] "GET / HTTP/1.1" 200 -]
[2025-01-03 20:59:35,563: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 45, in predictRoute
    return jsonify(result)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\admin\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\admin\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\admin\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type float32 is not JSON serializable
[2025-01-03 20:59:35,599: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 20:59:35] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 21:05:00,474: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 21:05:01,137: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.20.10.2:8080]
[2025-01-03 21:05:01,137: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 21:05:19,471: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:05:19] "GET / HTTP/1.1" 200 -]
[2025-01-03 21:05:46,580: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 30, in predict
    if max_confidence >= confidence_threshold:
NameError: name 'max_confidence' is not defined
[2025-01-03 21:05:46,637: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:05:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 21:08:46,124: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 21:08:46,958: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.20.10.2:8080]
[2025-01-03 21:08:46,959: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 21:08:53,869: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:08:53] "GET / HTTP/1.1" 200 -]
[2025-01-03 21:09:05,147: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:09:05] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:09:23,231: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:09:23] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:16:13,339: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 21:16:14,194: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.20.10.2:8080]
[2025-01-03 21:16:14,194: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 21:16:29,640: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:16:29] "GET / HTTP/1.1" 200 -]
[2025-01-03 21:18:10,511: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:18:10] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:18:50,916: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:18:50] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:19:06,827: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:19:06] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:21:15,702: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-01-03 21:21:16,483: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.20.10.2:8080]
[2025-01-03 21:21:16,483: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-03 21:21:22,666: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:21:22] "GET / HTTP/1.1" 200 -]
[2025-01-03 21:21:42,728: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    test_image = image.load_img(imagename, target_size=(224, 224))
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "C:\Users\admin\anaconda3\lib\site-packages\PIL\Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E729A29770>
[2025-01-03 21:21:42,739: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:21:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-03 21:21:52,948: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:21:52] "GET / HTTP/1.1" 200 -]
[2025-01-03 21:22:03,169: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:22:03] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:22:20,513: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:22:20] "POST /predict HTTP/1.1" 200 -]
[2025-01-03 21:22:33,638: INFO: _internal: 127.0.0.1 - - [03/Jan/2025 21:22:33] "POST /predict HTTP/1.1" 200 -]
[2025-02-05 14:36:24,548: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-02-05 14:36:26,190: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.44.1.72:8080]
[2025-02-05 14:36:26,197: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-05 14:36:58,987: INFO: _internal: 127.0.0.1 - - [05/Feb/2025 14:36:58] "GET / HTTP/1.1" 200 -]
[2025-02-05 14:38:11,448: INFO: _internal: 127.0.0.1 - - [05/Feb/2025 14:38:11] "POST /predict HTTP/1.1" 200 -]
[2025-02-18 10:25:08,146: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-02-18 10:25:08,951: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2025-02-18 10:25:08,953: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-18 10:25:33,164: INFO: _internal: 127.0.0.1 - - [18/Feb/2025 10:25:33] "GET / HTTP/1.1" 200 -]
[2025-02-18 10:26:20,170: INFO: _internal: 127.0.0.1 - - [18/Feb/2025 10:26:20] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:17:59,293: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-09 23:18:00,832: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.107:8080]
[2025-04-09 23:18:00,832: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-09 23:18:14,079: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:18:14] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:19:17,701: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:19:17] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:20:04,692: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:20:04] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:20:14,877: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:20:14] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:20:56,770: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:20:56] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:21:10,284: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:21:10] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:21:49,147: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001EF9E466EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-09 23:21:49,152: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:21:49] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:21:52,314: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001EF9E4660D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-09 23:21:52,318: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:21:52] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:21:58,066: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:21:58] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:22:00,246: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:22:00] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:22:09,741: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:22:09] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:22:16,067: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:22:16] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:22:27,367: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:22:27] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:22:59,309: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:22:59] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:23:07,361: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:23:07] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:26:54,240: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-09 23:26:55,530: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.107:8080]
[2025-04-09 23:26:55,531: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-09 23:27:03,315: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:27:03] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:27:09,969: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:27:09] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:36:35,523: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-09 23:36:36,688: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.107:8080]
[2025-04-09 23:36:36,688: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-09 23:36:45,300: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:36:45] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:36:49,911: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 34, in predict
    confidence = float(prediction[0][0])  # Tumor probability
NameError: name 'prediction' is not defined
[2025-04-09 23:36:49,918: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:36:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-09 23:37:05,774: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:37:05] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:37:06,759: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:37:06] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:37:15,349: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 34, in predict
    confidence = float(prediction[0][0])  # Tumor probability
NameError: name 'prediction' is not defined
[2025-04-09 23:37:15,351: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:37:15] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-09 23:37:36,163: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:37:36] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:37:40,310: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\anaconda3\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\admin\OneDrive\Desktop\7th Sem Project\Kidney-Disease-Classification-MLFlow-DVC\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\onedrive\desktop\7th sem project\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    test_image = image.load_img(imagename, target_size=(224, 224))
  File "C:\Users\admin\anaconda3\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "C:\Users\admin\anaconda3\lib\site-packages\PIL\Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002834D68CE50>
[2025-04-09 23:37:40,316: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:37:40] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-09 23:39:11,091: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-04-09 23:39:12,027: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.107:8080]
[2025-04-09 23:39:12,028: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-09 23:39:16,098: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:39:16] "GET / HTTP/1.1" 200 -]
[2025-04-09 23:39:21,798: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:39:21] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:39:30,258: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:39:30] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:39:42,565: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:39:42] "POST /predict HTTP/1.1" 200 -]
[2025-04-09 23:41:27,050: INFO: _internal: 127.0.0.1 - - [09/Apr/2025 23:41:27] "POST /predict HTTP/1.1" 200 -]
